from __future__ import unicode_literals

from django.db import models

class Team(models.Model):
    shop_entry_code = models.IntegerField(null=True)
    medianet_id = models.IntegerField(null=True)
    track_code = models.TextField(null=True)
    twitter = models.TextField(null=True)
    club_full_name = models.TextField(null=True)
    url_prod = models.TextField(null=True)
    dc_site = models.TextField(null=True)
    team_id = models.IntegerField(null=True)
    postal_code = models.TextField(null=True)
    instagram_id = models.IntegerField(null=True)
    timezone = models.TextField(null=True)
    team_code = models.CharField(max_length=5, null=True, unique=True)
    mlb_id = models.IntegerField(unique=True, null=True)
    mobile_es_url = models.TextField(null=True)
    esp_common_name = models.TextField(null=True)
    instagram = models.TextField(null=True)
    primary_link = models.TextField(null=True)
    display_code = models.TextField(null=True)
    venue_id = models.IntegerField(null=True)
    newsletter_group_id = models.IntegerField(null=True)
    pinterest = models.TextField(null=True)
    esp_common_url = models.TextField(null=True)
    club_id = models.IntegerField(null=True)
    url_esp = models.TextField(null=True)
    field = models.TextField(null=True)
    club_common_name = models.TextField(null=True)
    facebook_es = models.TextField(null=True)
    location = models.TextField(null=True)
    pressbox_url = models.TextField(null=True)
    pressbox_title = models.TextField(null=True)
    googleplus_id = models.TextField(null=True)
    fanphotos_url = models.TextField(null=True)
    division = models.TextField(null=True)
    name_display_long = models.TextField(null=True)
    mobile_short_code = models.TextField(null=True)
    fb_app_id = models.TextField(null=True)
    city = models.TextField(null=True)
    club = models.TextField(null=True)
    vine = models.TextField(null=True)
    photostore_url = models.TextField(null=True)
    track_filter = models.TextField(null=True)
    primary = models.TextField(null=True)
    es_track_code = models.TextField(null=True)
    newsletter_category_id = models.IntegerField(null=True)
    facebook = models.TextField(null=True)
    address = models.TextField(null=True)
    club_spanish_name = models.TextField(null=True)
    tumblr = models.TextField(null=True)
    google_tag_manager = models.TextField(null=True)
    twitter_es = models.TextField(null=True)
    secondary = models.TextField(null=True)
    state_province = models.TextField(null=True)
    league = models.TextField(null=True)
    club_common_url = models.TextField(null=True)
    phone = models.TextField(null=True)
    country = models.TextField(null=True)
    tertiary = models.TextField(null=True)
    pinterest_verification = models.TextField(null=True)
    name_display_short = models.TextField(null=True)
    url_cache = models.TextField(null=True)
    mobile_url_base = models.TextField(null=True)
    historical_team_code = models.TextField(null=True)
    mobile_url = models.TextField(null=True)
